"use client";

import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from './use-toast';
import {
  SeoMetadata,
  HeroSection,
  FeatureItem,
  PricingCta,
  seoMetadataSchema,
  heroSectionSchema,
  featuresSectionSchema,
  pricingCtaSchema,
} from '@/utils/landingPageSchemas';

// Default values (must match those in ManageLandingPage.tsx)
const defaultSeo: SeoMetadata = {
  metaTitle: "Prometric Exam Preparation for Gulf Countries | StudyPrometric – Online MCQs & Practice Tests",
  metaDescription: "Prepare for Prometric exams for Saudi Arabia, UAE, Qatar, Oman, Kuwait & Bahrain. Thousands of updated MCQs for doctors, nurses, and medical professionals. Start your free trial today!",
  keywords: "Prometric exam, Prometric exam preparation, DHA MOH HAAD exam questions, Gulf medical exam, SMLE MCQs, QCHP exam, OMSB exam, online Prometric test, Prometric practice test.",
};

const defaultHero: HeroSection = {
  mainTitle: "Master Your Medical Exams",
  subtitle: "Your ultimate platform for interactive quizzes, simulated tests, and AI-powered explanations to ace your Prometric MCQs.",
  ctaPrimaryText: "Get Started",
  ctaSecondaryText: "Take a Free Quiz",
};

const defaultFeatures: FeatureItem[] = [
  { icon: "BookOpenText", title: "Interactive Quizzes", description: "Engage with thousands of multiple-choice questions across various medical categories and subcategories. Track your progress and learn from detailed explanations." },
  { icon: "ClipboardCheck", title: "Simulated Tests", description: "Prepare for your exams with timed, customizable tests. Configure the number of questions, difficulty, and set a time limit to match your study needs." },
  { icon: "GraduationCap", title: "Structured Learning Paths", description: "Access comprehensive courses with organized topics, designed to guide you through complex medical subjects step-by-step." },
  { icon: "Brain", title: "AI-Powered Explanations", description: "Understand complex concepts with clear, concise explanations generated by advanced AI, including diagnostic tests and initial treatment plans." },
  { icon: "BrainCircuit", title: "AI Medical Assistant", description: "Get instant answers to your medical questions and exam queries with our integrated AI chatbot, available 24/7 to support your learning." },
  { icon: "CalendarDays", title: "Daily Challenge", description: "Test your knowledge with a new Question of the Day, track your points, and compete on the leaderboard for a chance to win a free subscription." },
  { icon: "Bookmark", title: "Bookmark & Review", description: "Save important or challenging MCQs to your personal bookmark list for easy access and focused review anytime." },
  { icon: "User", title: "Personalized Learning", description: "Your dashboard highlights areas for improvement and suggests practice topics based on your performance, ensuring efficient study." },
  { icon: "FilePlus", title: "Submit Your Own MCQs", description: "Contribute to our growing question bank by submitting your own MCQs for review. Share your knowledge and help the community." },
  { icon: "ShieldCheck", title: "Secure & Reliable", description: "Built with Supabase for robust authentication and data management, ensuring your learning journey is safe and seamless." },
];

const defaultPricingCta: PricingCta = {
  title: "Pricing Plans",
  subtitle: "Choose the plan that fits your study schedule and unlock premium features instantly.",
};


interface LandingPageSettings {
  seo: SeoMetadata;
  hero: HeroSection;
  features: FeatureItem[];
  pricingCta: PricingCta;
}

export const useLandingPageSettings = () => {
  const { toast } = useToast();
  const [settings, setSettings] = useState<LandingPageSettings>({
    seo: defaultSeo,
    hero: defaultHero,
    features: defaultFeatures,
    pricingCta: defaultPricingCta,
  });
  const [isLoading, setIsLoading] = useState(true);

  const fetchSettings = useCallback(async () => {
    setIsLoading(true);
    try {
      const { data, error } = await supabase
        .from('global_settings')
        .select('key, value')
        .in('key', ['seo_metadata', 'landing_page_hero', 'landing_page_features', 'landing_page_pricing_cta']);

      if (error) throw error;

      const newSettings: Partial<LandingPageSettings> = {};

      data.forEach(setting => {
        try {
          switch (setting.key) {
            case 'seo_metadata':
              newSettings.seo = seoMetadataSchema.parse(setting.value);
              break;
            case 'landing_page_hero':
              newSettings.hero = heroSectionSchema.parse(setting.value);
              break;
            case 'landing_page_features':
              newSettings.features = featuresSectionSchema.parse(setting.value);
              break;
            case 'landing_page_pricing_cta':
              newSettings.pricingCta = pricingCtaSchema.parse(setting.value);
              break;
          }
        } catch (e) {
          console.error(`Validation failed for setting key ${setting.key}:`, e);
          // Fallback to default if validation fails
        }
      });

      setSettings({
        seo: newSettings.seo || defaultSeo,
        hero: newSettings.hero || defaultHero,
        features: newSettings.features || defaultFeatures,
        pricingCta: newSettings.pricingCta || defaultPricingCta,
      });

    } catch (error: any) {
      console.error("Error fetching landing page settings:", error);
      toast({ title: "Error", description: "Failed to load dynamic landing page content.", variant: "destructive" });
      // Ensure defaults are used on failure
      setSettings({
        seo: defaultSeo,
        hero: defaultHero,
        features: defaultFeatures,
        pricingCta: defaultPricingCta,
      });
    } finally {
      setIsLoading(false);
    }
  }, [toast]);

  useEffect(() => {
    fetchSettings();
  }, [fetchSettings]);

  return { settings, isLoading };
};