"use client";

import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardDescription, CardTitle } from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { BookOpenText, ClipboardCheck, User, FilePlus, ShieldCheck, Brain, CalendarDays, GraduationCap, Bookmark } from 'lucide-react'; // Re-import LayoutDashboard
import { useSession } from '@/components/SessionContextProvider';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { Input } from '@/components/ui/input'; // Import Input
import { useForm } from 'react-hook-form'; // Import useForm
import { zodResolver } from '@hookform/resolvers/zod'; // Import zodResolver
import * as z from 'zod'; // Import zod
import { Form, FormControl, FormField, FormItem, FormMessage } from '@/components/ui/form'; // Import Form components

// Define a type for FAQ items
interface FaqItem {
  question: string;
  answer: string;
}

// Define a type for FAQ categories (simplified for landing page display)
interface FaqCategory {
  category: string;
  questions: FaqItem[];
}

const features = [
  {
    icon: <BookOpenText className="h-8 w-8 text-primary" />,
    title: "Interactive Quizzes",
    description: "Engage with thousands of multiple-choice questions across various medical categories and subcategories. Track your progress and learn from detailed explanations.",
  },
  {
    icon: <ClipboardCheck className="h-8 w-8 text-primary" />,
    title: "Simulated Tests",
    description: "Prepare for your exams with timed, customizable tests. Configure the number of questions, difficulty, and set a time limit to match your study needs.",
  },
  {
    icon: <GraduationCap className="h-8 w-8 text-primary" />,
    title: "Structured Learning Paths",
    description: "Access comprehensive courses with organized topics, designed to guide you through complex medical subjects step-by-step.",
  },
  {
    icon: <Brain className="h-8 w-8 text-primary" />,
    title: "AI-Powered Explanations",
    description: "Understand complex concepts with clear, concise explanations generated by advanced AI, including diagnostic tests and initial treatment plans.",
  },
  {
    icon: <CalendarDays className="h-8 w-8 text-primary" />,
    title: "Daily Challenge",
    description: "Test your knowledge with a new Question of the Day, track your points, and compete on the leaderboard for a chance to win a free subscription.",
  },
  {
    icon: <Bookmark className="h-8 w-8 text-primary" />,
    title: "Bookmark & Review",
    description: "Save important or challenging MCQs to your personal bookmark list for easy access and focused review anytime.",
  },
  {
    icon: <User className="h-8 w-8 text-primary" />,
    title: "Personalized Learning",
    description: "Your dashboard highlights areas for improvement and suggests practice topics based on your performance, ensuring efficient study.",
  },
  {
    icon: <FilePlus className="h-8 w-8 text-primary" />,
    title: "Submit Your Own MCQs",
    description: "Contribute to our growing question bank by submitting your own MCQs for review. Share your knowledge and help the community.",
  },
  {
    icon: <ShieldCheck className="h-8 w-8 text-primary" />,
    title: "Secure & Reliable",
    description: "Built with Supabase for robust authentication and data management, ensuring your learning journey is safe and seamless.",
  },
];

const defaultFaqItems: FaqCategory[] = [
  {
    category: "General Questions",
    questions: [
      {
        question: "What is Study Prometric MCQs?",
        answer: "Study Prometric MCQs is an online platform designed to help medical students and professionals prepare for their exams through interactive quizzes, simulated tests, and AI-powered explanations.",
      },
      {
        question: "How do I get started?",
        answer: "You can start by signing up for a free trial to access a limited set of questions, or subscribe to one of our plans for full access to all features and our extensive question bank.",
      },
      {
        question: "Is there a free trial?",
        answer: "Yes, we offer a free trial that allows you to attempt a limited number of questions to experience our platform before committing to a subscription.",
      },
      {
        question: "What payment methods do you accept?",
        answer: "We currently accept payments via PayPal, ensuring a secure and convenient transaction process.",
      },
    ],
  },
];

const marketingFormSchema = z.object({
  email: z.string().email("Invalid email address.").min(1, "Email is required."),
});

const LandingPage = () => {
  const { user, hasCheckedInitialSession } = useSession();
  const { toast } = useToast();
  const [faqItems, setFaqItems] = useState<FaqCategory[]>(defaultFaqItems);
  const [isLoadingFaq, setIsLoadingFaq] = useState(true);
  const [isSubscribing, setIsSubscribing] = useState(false);

  const marketingForm = useForm<z.infer<typeof marketingFormSchema>>({
    resolver: zodResolver(marketingFormSchema),
    defaultValues: {
      email: "",
    },
  });

  useEffect(() => {
    const fetchFaqContent = async () => {
      setIsLoadingFaq(true);
      const { data, error } = await supabase
        .from('static_pages')
        .select('content')
        .eq('slug', 'faq')
        .single();

      if (error && error.code !== 'PGRST116') { // PGRST116 means no rows found
        console.error('Error fetching FAQ content for landing page:', error);
        toast({ title: "Error", description: "Failed to load FAQ content for landing page.", variant: "destructive" });
      } else if (data) {
        try {
          const parsedContent = JSON.parse(data.content || '[]');
          if (Array.isArray(parsedContent) && parsedContent.every(item => 'category' in item && 'questions' in item)) {
            // Take only the first category's questions for the landing page, or a limited number
            const landingPageFaqs = parsedContent.slice(0, 1).flatMap(cat => cat.questions.slice(0, 4)); // Max 4 questions
            setFaqItems([{ category: "Frequently Asked Questions", questions: landingPageFaqs }]);
          } else {
            console.warn("FAQ content from DB is not in expected format, using default for landing page.");
            setFaqItems(defaultFaqItems);
          }
        } catch (parseError) {
          console.error("Error parsing FAQ content from DB for landing page:", parseError);
          setFaqItems(defaultFaqItems);
        }
      }
      setIsLoadingFaq(false);
    };

    fetchFaqContent();
  }, [toast]);

  const handleMarketingSubscribe = async (values: z.infer<typeof marketingFormSchema>) => {
    setIsSubscribing(true);
    console.log('Client: Attempting to subscribe marketing email:', values.email); // Client-side log
    try {
      const { data, error } = await supabase.functions.invoke('subscribe-marketing-email', {
        body: { email: values.email },
      });
      console.log('Client: Supabase function invoke response - data:', data, 'error:', error); // Client-side log

      if (error) {
        if (error.status === 409) { // Conflict, email already subscribed
          toast({
            title: "Already Subscribed",
            description: "This email is already on our mailing list!",
            variant: "default",
          });
        } else {
          throw error;
        }
      } else {
        toast({
          title: "Subscription Successful!",
          description: data.message || "Check your inbox for a confirmation email.", // Explicitly use data.message
          variant: "default",
        });
        marketingForm.reset();
      }
    } catch (error: any) {
      console.error("Client: Marketing subscription error:", error); // Client-side error log
      toast({
        title: "Subscription Failed",
        description: `Failed to subscribe: ${error.message || 'Unknown error'}`,
        variant: "destructive",
      });
    } finally {
      setIsSubscribing(false);
      console.log('Client: Marketing subscription process finished.'); // Client-side log
    }
  };

  if (!hasCheckedInitialSession) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-100 dark:bg-gray-900">
        <p className="text-gray-700 dark:text-gray-300">Loading...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background text-foreground pt-16">
      {/* Hero Section */}
      <section className="relative w-full py-20 md:py-32 bg-gradient-to-r from-primary to-blue-600 text-primary-foreground text-center overflow-hidden">
        <div className="container mx-auto px-4 relative z-10">
          <h1 className="text-4xl md:text-6xl font-extrabold leading-tight mb-6 animate-fade-in-up">
            Master Your Medical Exams
          </h1>
          <p className="text-lg md:text-xl mb-10 max-w-3xl mx-auto opacity-90 animate-fade-in-up delay-200">
            Your ultimate platform for interactive quizzes, simulated tests, and AI-powered explanations to ace your Prometric MCQs.
          </p>
          <div className="flex flex-col justify-center gap-4 max-w-sm mx-auto sm:flex-row sm:max-w-none animate-fade-in-up delay-400">
            {user ? (
              <Link to={user.is_admin ? "/admin/dashboard" : "/user/dashboard"} className="w-full sm:w-auto">
                <Button size="lg" className="bg-primary-foreground text-primary hover:bg-primary-foreground/90 w-full">
                  Go to Dashboard
                </Button>
              </Link>
            ) : (
              <>
                <Link to="/subscription" className="w-full sm:w-auto">
                  <Button size="lg" className="bg-primary-foreground text-primary hover:bg-primary-foreground/90 w-full">
                    Get Started
                  </Button>
                </Link>
                <Link to="/quiz" className="w-full sm:w-auto">
                  <Button size="lg" variant="secondary" className="flex items-center gap-2 w-full">
                    <BookOpenText className="h-5 w-5" /> Take a Free Quiz
                  </Button>
                </Link>
                <Link to="/quiz-of-the-day" className="w-full sm:w-auto">
                  <Button size="lg" variant="secondary" className="flex items-center gap-2 w-full">
                    <CalendarDays className="h-5 w-5" /> Question of the Day
                  </Button>
                </Link>
                <Link to="/user/courses" className="w-full sm:w-auto">
                  <Button size="lg" variant="secondary" className="flex items-center gap-2 w-full">
                    <GraduationCap className="h-5 w-5" /> Browse Courses
                  </Button>
                </Link>
              </>
            )}
          </div>
        </div>
        {/* Background shapes for visual appeal */}
        <div className="absolute inset-0 z-0 opacity-20">
          <div className="absolute top-1/4 left-1/4 w-64 h-64 bg-blue-400 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob"></div>
          <div className="absolute top-1/2 right-1/4 w-72 h-72 bg-purple-400 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-2000"></div>
          <div className="absolute bottom-1/4 left-1/2 w-80 h-80 bg-pink-400 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-4000"></div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 md:py-24 bg-background">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">Why Choose Us?</h2>
          <p className="text-lg text-muted-foreground mb-12 max-w-2xl mx-auto">
            Unlock your full potential with our comprehensive and intelligent learning tools.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <Card key={index} className="flex flex-col items-center p-6 text-center hover:shadow-lg transition-shadow duration-300">
                <div className="mb-4 p-3 rounded-full bg-primary/10">
                  {feature.icon}
                </div>
                <CardTitle className="text-xl mb-2">{feature.title}</CardTitle>
                <CardDescription className="text-muted-foreground">{feature.description}</CardDescription>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Marketing Email Subscription Section */}
      <section className="py-16 md:py-24 bg-secondary text-secondary-foreground text-center">
        <div className="container mx-auto px-4 max-w-2xl">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">Stay Updated!</h2>
          <p className="text-lg mb-8">
            Subscribe to our newsletter for daily quiz updates, study tips, and special offers.
          </p>
          <Form {...marketingForm}>
            <form onSubmit={marketingForm.handleSubmit(handleMarketingSubscribe)} className="flex flex-col sm:flex-row gap-4 max-w-md mx-auto">
              <FormField
                control={marketingForm.control}
                name="email"
                render={({ field }) => (
                  <FormItem className="flex-grow">
                    <FormControl>
                      <Input
                        type="email"
                        placeholder="Enter your email"
                        className="h-12 text-lg"
                        disabled={isSubscribing}
                        {...field}
                      />
                    </FormControl>
                    <FormMessage className="text-left" />
                  </FormItem>
                )}
              />
              <Button type="submit" size="lg" className="h-12 text-lg w-full sm:w-auto" disabled={isSubscribing}>
                {isSubscribing ? "Subscribing..." : "Subscribe"}
              </Button>
            </form>
          </Form>
        </div>
      </section>

      {/* Call to Action Section */}
      <section className="py-16 md:py-24 bg-primary text-primary-foreground text-center">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">Ready to Boost Your Scores?</h2>
          <p className="text-lg mb-8 max-w-2xl mx-auto">
            Join thousands of students who are already excelling with Study Prometric MCQs.
          </p>
          <Link to="/subscription">
            <Button size="lg" className="bg-primary-foreground text-primary hover:bg-primary-foreground/90">
              Start Your Journey Today
            </Button>
          </Link>
        </div>
      </section>

      {/* FAQ Section (Embedded) */}
      <section className="py-16 md:py-24 bg-background">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl md:text-4xl font-bold text-center mb-12">Frequently Asked Questions</h2>
          <div className="max-w-3xl mx-auto">
            {isLoadingFaq ? (
              <p className="text-center text-gray-600 dark:text-gray-400">Loading FAQs...</p>
            ) : (
              <Accordion type="single" collapsible className="w-full">
                {faqItems.flatMap((category, catIndex) =>
                  category.questions.map((item, qIndex) => (
                    <AccordionItem key={`${catIndex}-${qIndex}`} value={`item-${catIndex}-${qIndex}`}>
                      <AccordionTrigger className="text-left text-lg font-medium">{item.question}</AccordionTrigger>
                      <AccordionContent className="text-muted-foreground text-base">
                        {item.answer}
                      </AccordionContent>
                    </AccordionItem>
                  ))
                )}
              </Accordion>
            )}
            <p className="text-center text-muted-foreground mt-8">
              Have more questions? Visit our dedicated <Link to="/faq" className="text-primary hover:underline">FAQ Page</Link>.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
};

export default LandingPage;