"use client";

import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardDescription, CardTitle } from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { BookOpenText, ClipboardCheck, User, FilePlus, ShieldCheck, Brain } from 'lucide-react';
import { useSession } from '@/components/SessionContextProvider';

const features = [
  {
    icon: <BookOpenText className="h-8 w-8 text-primary" />,
    title: "Interactive Quizzes",
    description: "Engage with thousands of multiple-choice questions across various medical categories and subcategories. Track your progress and learn from detailed explanations.",
  },
  {
    icon: <ClipboardCheck className="h-8 w-8 text-primary" />,
    title: "Simulated Tests",
    description: "Prepare for your exams with timed, customizable tests. Configure the number of questions, difficulty, and categories to match your study needs.",
  },
  {
    icon: <Brain className="h-8 w-8 text-primary" />,
    title: "AI-Powered Explanations",
    description: "Understand complex concepts with clear, concise explanations generated by advanced AI, including diagnostic tests and initial treatment plans.",
  },
  {
    icon: <User className="h-8 w-8 text-primary" />,
    title: "Personalized Learning",
    description: "Your dashboard highlights areas for improvement and suggests practice topics based on your performance, ensuring efficient study.",
  },
  {
    icon: <FilePlus className="h-8 w-8 text-primary" />,
    title: "Submit Your Own MCQs",
    description: "Contribute to our growing question bank by submitting your own MCQs for review. Share your knowledge and help the community.",
  },
  {
    icon: <ShieldCheck className="h-8 w-8 text-primary" />,
    title: "Secure & Reliable",
    description: "Built with Supabase for robust authentication and data management, ensuring your learning journey is safe and seamless.",
  },
];

const faqItems = [
  {
    question: "What is Study Prometric MCQs?",
    answer: "Study Prometric MCQs is an online platform designed to help medical students and professionals prepare for their exams through interactive quizzes, simulated tests, and AI-powered explanations.",
  },
  {
    question: "How do I get started?",
    answer: "You can start by signing up for a free trial to access a limited set of questions, or subscribe to one of our plans for full access to all features and our extensive question bank.",
  },
  {
    question: "Is there a free trial?",
    answer: "Yes, we offer a free trial that allows you to attempt a limited number of questions to experience our platform before committing to a subscription.",
  },
  {
    question: "What payment methods do you accept?",
    answer: "We currently accept payments via PayPal, ensuring a secure and convenient transaction process.",
  },
];

const LandingPage = () => {
  const { user, hasCheckedInitialSession } = useSession();

  if (!hasCheckedInitialSession) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-100 dark:bg-gray-900">
        <p className="text-gray-700 dark:text-gray-300">Loading...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background text-foreground pt-16"> {/* Added pt-16 for fixed header */}
      {/* Hero Section */}
      <section className="relative w-full py-20 md:py-32 bg-gradient-to-r from-primary to-blue-600 text-primary-foreground text-center overflow-hidden">
        <div className="container mx-auto px-4 relative z-10">
          <h1 className="text-4xl md:text-6xl font-extrabold leading-tight mb-6 animate-fade-in-up">
            Master Your Medical Exams
          </h1>
          <p className="text-lg md:text-xl mb-10 max-w-3xl mx-auto opacity-90 animate-fade-in-up delay-200">
            Your ultimate platform for interactive quizzes, simulated tests, and AI-powered explanations to ace your Prometric MCQs.
          </p>
          <div className="flex flex-col sm:flex-row justify-center gap-4 animate-fade-in-up delay-400">
            {user ? (
              <Link to={user.is_admin ? "/admin/dashboard" : "/user/dashboard"}>
                <Button size="lg" className="bg-primary-foreground text-primary hover:bg-primary-foreground/90">
                  Go to Dashboard
                </Button>
              </Link>
            ) : (
              <>
                <Link to="/subscription">
                  <Button size="lg" className="bg-primary-foreground text-primary hover:bg-primary-foreground/90">
                    Get Started
                  </Button>
                </Link>
                <Link to="/user/dashboard"> {/* Redirect to user dashboard for guest mode */}
                  <Button size="lg" variant="secondary">
                    Try a Free Quiz
                  </Button>
                </Link>
              </>
            )}
          </div>
        </div>
        {/* Background shapes for visual appeal */}
        <div className="absolute inset-0 z-0 opacity-20">
          <div className="absolute top-1/4 left-1/4 w-64 h-64 bg-blue-400 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob"></div>
          <div className="absolute top-1/2 right-1/4 w-72 h-72 bg-purple-400 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-2000"></div>
          <div className="absolute bottom-1/4 left-1/2 w-80 h-80 bg-pink-400 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-4000"></div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 md:py-24 bg-background">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">Why Choose Us?</h2>
          <p className="text-lg text-muted-foreground mb-12 max-w-2xl mx-auto">
            Unlock your full potential with our comprehensive and intelligent learning tools.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <Card key={index} className="flex flex-col items-center p-6 text-center hover:shadow-lg transition-shadow duration-300">
                <div className="mb-4 p-3 rounded-full bg-primary/10">
                  {feature.icon}
                </div>
                <CardTitle className="text-xl mb-2">{feature.title}</CardTitle>
                <CardDescription className="text-muted-foreground">{feature.description}</CardDescription>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Call to Action Section */}
      <section className="py-16 md:py-24 bg-secondary text-secondary-foreground text-center">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">Ready to Boost Your Scores?</h2>
          <p className="text-lg mb-8 max-w-2xl mx-auto">
            Join thousands of students who are already excelling with Study Prometric MCQs.
          </p>
          <Link to="/subscription">
            <Button size="lg" className="bg-primary text-primary-foreground hover:bg-primary/90">
              Start Your Journey Today
            </Button>
          </Link>
        </div>
      </section>

      {/* FAQ Section (Embedded) */}
      <section className="py-16 md:py-24 bg-background">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl md:text-4xl font-bold text-center mb-12">Frequently Asked Questions</h2>
          <div className="max-w-3xl mx-auto">
            <Accordion type="single" collapsible className="w-full">
              {faqItems.map((item, index) => (
                <AccordionItem key={index} value={`item-${index}`}>
                  <AccordionTrigger className="text-left text-lg font-medium">{item.question}</AccordionTrigger>
                  <AccordionContent className="text-muted-foreground text-base">
                    {item.answer}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
            <p className="text-center text-muted-foreground mt-8">
              Have more questions? Visit our dedicated <Link to="/faq" className="text-primary hover:underline">FAQ Page</Link>.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
};

export default LandingPage;