// This file is automatically generated.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uvhlyitcrogvssmcqtni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2aGx5aXRjcm9ndnNzbWNxdG5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1OTY2NjYsImV4cCI6MjA3NDE3MjY2Nn0.a8YqxWp2sLfiZznopSqrc1UXoGKNEa3077JFd54JjDc";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
        storageKey: 'study-prometric-auth-token' // Use a specific key to avoid conflicts with other apps
    }
});